### ISSUE TITLE
Having issues with Interaction Service

### ISSUE THREAD

**Issue by SleepyZzed** [zobweyt/Discord.NET-Template#1]
![image](https://user-images.githubusercontent.com/48292912/188336828-542048ef-39cd-4d53-b4d8-86f70687aab8.png)
been trying to get slash commands working have set up my token bot logs in and have the slash commands showing up in discord but the bot doesn't respond to them

**Comment by zobweyt** [comment]
Does it work with other commands? The error comes from the `avatar` command.
